package main.java.com.store.resources.dao;

import java.util.List;
import main.java.com.store.resources.mappers.Product;
import main.java.com.store.resources.mappers.ProductExample;
import org.apache.ibatis.annotations.Param;

public interface ProductMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table products
	 * @mbggenerated  Mon Apr 20 12:01:29 ART 2015
	 */
	int countByExample(ProductExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table products
	 * @mbggenerated  Mon Apr 20 12:01:29 ART 2015
	 */
	int deleteByExample(ProductExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table products
	 * @mbggenerated  Mon Apr 20 12:01:29 ART 2015
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table products
	 * @mbggenerated  Mon Apr 20 12:01:29 ART 2015
	 */
	int insert(Product record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table products
	 * @mbggenerated  Mon Apr 20 12:01:29 ART 2015
	 */
	int insertSelective(Product record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table products
	 * @mbggenerated  Mon Apr 20 12:01:29 ART 2015
	 */
	List<Product> selectByExample(ProductExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table products
	 * @mbggenerated  Mon Apr 20 12:01:29 ART 2015
	 */
	Product selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table products
	 * @mbggenerated  Mon Apr 20 12:01:29 ART 2015
	 */
	int updateByExampleSelective(@Param("record") Product record,
			@Param("example") ProductExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table products
	 * @mbggenerated  Mon Apr 20 12:01:29 ART 2015
	 */
	int updateByExample(@Param("record") Product record,
			@Param("example") ProductExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table products
	 * @mbggenerated  Mon Apr 20 12:01:29 ART 2015
	 */
	int updateByPrimaryKeySelective(Product record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table products
	 * @mbggenerated  Mon Apr 20 12:01:29 ART 2015
	 */
	int updateByPrimaryKey(Product record);
}