package main.java.com.store.resources.mappers;

import java.math.BigDecimal;

public class Product {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column products.id
	 * @mbggenerated  Mon Apr 20 12:01:29 ART 2015
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column products.name
	 * @mbggenerated  Mon Apr 20 12:01:29 ART 2015
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column products.price
	 * @mbggenerated  Mon Apr 20 12:01:29 ART 2015
	 */
	private BigDecimal price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column products.description
	 * @mbggenerated  Mon Apr 20 12:01:29 ART 2015
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column products.stock
	 * @mbggenerated  Mon Apr 20 12:01:29 ART 2015
	 */
	private Integer stock;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column products.id
	 * @return  the value of products.id
	 * @mbggenerated  Mon Apr 20 12:01:29 ART 2015
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column products.id
	 * @param id  the value for products.id
	 * @mbggenerated  Mon Apr 20 12:01:29 ART 2015
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column products.name
	 * @return  the value of products.name
	 * @mbggenerated  Mon Apr 20 12:01:29 ART 2015
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column products.name
	 * @param name  the value for products.name
	 * @mbggenerated  Mon Apr 20 12:01:29 ART 2015
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column products.price
	 * @return  the value of products.price
	 * @mbggenerated  Mon Apr 20 12:01:29 ART 2015
	 */
	public BigDecimal getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column products.price
	 * @param price  the value for products.price
	 * @mbggenerated  Mon Apr 20 12:01:29 ART 2015
	 */
	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column products.description
	 * @return  the value of products.description
	 * @mbggenerated  Mon Apr 20 12:01:29 ART 2015
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column products.description
	 * @param description  the value for products.description
	 * @mbggenerated  Mon Apr 20 12:01:29 ART 2015
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column products.stock
	 * @return  the value of products.stock
	 * @mbggenerated  Mon Apr 20 12:01:29 ART 2015
	 */
	public Integer getStock() {
		return stock;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column products.stock
	 * @param stock  the value for products.stock
	 * @mbggenerated  Mon Apr 20 12:01:29 ART 2015
	 */
	public void setStock(Integer stock) {
		this.stock = stock;
	}
}